//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<sv_Orders> sv_Orders { get; set; }
        public virtual DbSet<AspNet_SqlCacheTablesForChangeNotification> AspNet_SqlCacheTablesForChangeNotification { get; set; }
        public virtual DbSet<sv_Orderslyh> sv_Orderslyh { get; set; }
    
        public virtual ObjectResult<AspNet_SqlCachePollingStoredProcedure_Result> AspNet_SqlCachePollingStoredProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AspNet_SqlCachePollingStoredProcedure_Result>("AspNet_SqlCachePollingStoredProcedure");
        }
    
        public virtual ObjectResult<string> AspNet_SqlCacheQueryRegisteredTablesStoredProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AspNet_SqlCacheQueryRegisteredTablesStoredProcedure");
        }
    
        public virtual int AspNet_SqlCacheRegisterTableStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheRegisterTableStoredProcedure", tableNameParameter);
        }
    
        public virtual int AspNet_SqlCacheUnRegisterTableStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheUnRegisterTableStoredProcedure", tableNameParameter);
        }
    
        public virtual int AspNet_SqlCacheUpdateChangeIdStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheUpdateChangeIdStoredProcedure", tableNameParameter);
        }
    }
}
